version: "3.9"
services:
  control:
    image: fercevik/stlker-control
    build: control
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
      - grpc
      - redis
    environment:
      - DB_PASS=${DB_PASS}
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
  grpc:
    image: fercevik/stlker-grpc
    build: grpc
    ports:
      - "127.0.0.1:9090:9090"
    environment:
      - API_KEY=${API_KEY}
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=stlker
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

