version: "3.9"
services:
  control:
    build: "./control"
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
      - grpc
      - redis
  redis:
    image: redis
  grpc:
    build: "./grpc"
    ports:
      - "127.0.0.1:9090:9090"
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
