basePath: /
consumes:
    - application/json
definitions:
    MoreStock:
        description: MoreStock contains important financial metrics
        x-go-package: github.com/fercevik729/STLKER/control/handlers
    Portfolio:
        description: A Portfolio defines the structure for an API portfolio
        x-go-package: github.com/fercevik729/STLKER/control/handlers
    Profits:
        description: A Profits struct defines the structure for the profits of an API portfoli
        x-go-package: github.com/fercevik729/STLKER/control/handlers
    Security:
        description: Product defines the structure for an API product
        x-go-package: github.com/fercevik729/STLKER/control/handlers
    Stock:
        description: Stock is the struct equivalent to the body returned by the gRPC API
        x-go-package: github.com/fercevik729/STLKER/control/handlers
info:
    description: Documentation for STLKER API
    title: of STLKER API
    version: 1.0.0
paths:
    /portfolios:
        get:
            description: Outputs all of the portfolios for a user
            operationId: getPortfolios
            responses:
                "200":
                    $ref: '#/responses/profitsResponse'
                "400":
                    $ref: '#/responses/errorResponse'
                "500":
                    $ref: '#/responses/errorResponse'
            tags:
                - portfolios
        post:
            description: Creates a new portfolio for a user
            operationId: createPortfolio
            parameters:
            - description: A portfolio
              in: body
              name: Body
              schema:
                $ref: '#/definitions/Portfolio'
            responses:
                "200":
                    $ref: '#/responses/messageResponse'
                "400":
                    $ref: '#/responses/errorResponse'
                "500":
                    $ref: '#/responses/errorResponse'
            tags:
                - portfolios
        put:
            description: Updates a given portfolio
            operationId: updatePortfolio
            parameters:
            - description: A portfolio
              in: body
              name: Body
              schema:
                $ref: '#/definitions/Portfolio'
            responses:
                "200":
                    $ref: '#/responses/messageResponse'
                "400":
                    $ref: '#/responses/errorResponse'
                "500":
                    $ref: '#/responses/errorResponse'
            tags:
                - portfolios
    /portfolios/{name}:
        delete:
            description: Deletes a given portfolio for a user
            operationId: deletePortfolio
            parameters:
                - description: Name of the portfolio
                  in: path
                  name: name
                  required: true
                  type: string
                  x-go-name: Name
            responses:
                "200":
                    $ref: '#/responses/messageResponse'
                "400":
                    $ref: '#/responses/errorResponse'
                "500":
                    $ref: '#/responses/errorResponse'
            tags:
                - securities
        get:
            description: Outputs a particulare portfolio for a user
            operationId: getPortfolio
            parameters:
                - description: Name of the portfolio
                  in: path
                  name: name
                  required: true
                  type: string
                  x-go-name: Name
            responses:
                "200":
                    $ref: '#/responses/profitResponse'
                "400":
                    $ref: '#/responses/errorResponse'
                "500":
                    $ref: '#/responses/errorResponse'
            tags:
                - portfolios
        post:
            description: Creates a new security
            operationId: createSecurity
            parameters:
                - description: Name of the portfolio
                  in: path
                  name: name
                  required: true
                  type: string
                  x-go-name: Name
            responses:
                "200":
                    $ref: '#/responses/messageResponse'
                "400":
                    $ref: '#/responses/errorResponse'
                "500":
                    $ref: '#/responses/errorResponse'
            tags:
                - securities
        put:
            description: Updates a security's information for a given portfolio
            operationId: updateSecurity
            parameters:
                - description: Name of the portfolio
                  in: path
                  name: name
                  required: true
                  type: string
                  x-go-name: Name
            responses:
                "200":
                    $ref: '#/responses/messageResponse'
                "400":
                    $ref: '#/responses/errorResponse'
                "500":
                    $ref: '#/responses/errorResponse'
            tags:
                - securities
    /portfolios/{name}/{ticker}:
        delete:
            description: Deletes a security from a given portfolio
            operationId: deleteSecurity
            parameters:
                - description: Name of the portfolio
                  in: path
                  name: name
                  required: true
                  type: string
                  x-go-name: Name
                - description: Ticker of the security
                  in: path
                  name: ticker
                  required: true
                  type: string
                  x-go-name: Ticker
            responses:
                "200":
                    $ref: '#/responses/messageResponse'
                "400":
                    $ref: '#/responses/errorResponse'
                "500":
                    $ref: '#/responses/errorResponse'
            tags:
                - securities
        get:
            description: Outputs a security's details to the client
            operationId: readSecurity
            parameters:
                - description: Name of the portfolio
                  in: path
                  name: name
                  required: true
                  type: string
                  x-go-name: Name
                - description: Ticker of the security
                  in: path
                  name: ticker
                  required: true
                  type: string
                  x-go-name: Ticker
            responses:
                "200":
                    $ref: '#/responses/securityResponse'
                "400":
                    $ref: '#/responses/errorResponse'
                "500":
                    $ref: '#/responses/errorResponse'
            tags:
                - securities
    /stocks/{ticker}/{currency}:
        get:
            description: Outputs a stock's financial details to the client in the requested currency
            operationId: getInfo
            parameters:
                - description: Ticker of the security
                  in: path
                  name: ticker
                  required: true
                  type: string
                  x-go-name: Ticker
                - description: Destination currency for the security's unit prices
                  in: path
                  name: currency
                  required: true
                  type: string
                  x-go-name: Currency
            responses:
                "200":
                    $ref: '#/responses/stockResponse'
                "400":
                    $ref: '#/responses/errorResponse'
                "500":
                    $ref: '#/responses/errorResponse'
            tags:
                - stocks
    /stocks/more/{ticker}:
        get:
            description: Outputs more sophisticated stock informations
            operationId: moreInfo
            parameters:
                - description: Ticker of the security
                  in: path
                  name: ticker
                  required: true
                  type: string
                  x-go-name: Ticker
            responses:
                "200":
                    $ref: '#/responses/moreStockResponse'
                "400":
                    $ref: '#/responses/errorResponse'
                "500":
                    $ref: '#/responses/errorResponse'
            tags:
                - stocks
produces:
    - application/json
responses:
    errorResponse:
        description: An errorResponse is an empty data structure to represent an http error
    messageResponse:
        description: A messageResponse is diagnostic information returned to the client
    moreStockResponse:
        description: A moreStockResponse is more information about a single stock
        schema:
          $ref: '#/definitions/MoreStock'
    profitResponse:
        description: A profitResponse is a single portfolio returned to the client
        schema:
          $ref: '#/definitions/Profits'
    profitsResponse:
        description: A profits is a list of profits for each of the portfolios returned to the client
        schema:
          items:
            $ref: '#/definitions/Profits'
          type: array
    securityResponse:
        description: A securityResponse is a single security's information returned to the client
        schema:
          $ref: '#/definitions/Security'
    stockResponse:
        description: A stockResponse is information about a single stock returned to the client
        schema:
          $ref: '#/definitions/Stock'
schemes:
    - http
swagger: "2.0"
