// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/watcher.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TickerRequest struct {
	Ticker               string   `protobuf:"bytes,1,opt,name=Ticker,proto3" json:"Ticker,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TickerRequest) Reset()         { *m = TickerRequest{} }
func (m *TickerRequest) String() string { return proto.CompactTextString(m) }
func (*TickerRequest) ProtoMessage()    {}
func (*TickerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_606cf1056908c0d2, []int{0}
}

func (m *TickerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TickerRequest.Unmarshal(m, b)
}
func (m *TickerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TickerRequest.Marshal(b, m, deterministic)
}
func (m *TickerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TickerRequest.Merge(m, src)
}
func (m *TickerRequest) XXX_Size() int {
	return xxx_messageInfo_TickerRequest.Size(m)
}
func (m *TickerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TickerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TickerRequest proto.InternalMessageInfo

func (m *TickerRequest) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

type TickerResponse struct {
	StockPrice           float32  `protobuf:"fixed32,1,opt,name=StockPrice,proto3" json:"StockPrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TickerResponse) Reset()         { *m = TickerResponse{} }
func (m *TickerResponse) String() string { return proto.CompactTextString(m) }
func (*TickerResponse) ProtoMessage()    {}
func (*TickerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_606cf1056908c0d2, []int{1}
}

func (m *TickerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TickerResponse.Unmarshal(m, b)
}
func (m *TickerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TickerResponse.Marshal(b, m, deterministic)
}
func (m *TickerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TickerResponse.Merge(m, src)
}
func (m *TickerResponse) XXX_Size() int {
	return xxx_messageInfo_TickerResponse.Size(m)
}
func (m *TickerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TickerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TickerResponse proto.InternalMessageInfo

func (m *TickerResponse) GetStockPrice() float32 {
	if m != nil {
		return m.StockPrice
	}
	return 0
}

func init() {
	proto.RegisterType((*TickerRequest)(nil), "TickerRequest")
	proto.RegisterType((*TickerResponse)(nil), "TickerResponse")
}

func init() { proto.RegisterFile("protos/watcher.proto", fileDescriptor_606cf1056908c0d2) }

var fileDescriptor_606cf1056908c0d2 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x2f, 0x4f, 0x2c, 0x49, 0xce, 0x48, 0x2d, 0xd2, 0x03, 0x73, 0x95, 0xd4, 0xb9,
	0x78, 0x43, 0x32, 0x93, 0xb3, 0x53, 0x8b, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xc4,
	0xb8, 0xd8, 0x20, 0x02, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x50, 0x9e, 0x92, 0x01, 0x17,
	0x1f, 0x4c, 0x61, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0xaa, 0x90, 0x1c, 0x17, 0x57, 0x70, 0x49, 0x7e,
	0x72, 0x76, 0x40, 0x51, 0x66, 0x72, 0x2a, 0x58, 0x35, 0x53, 0x10, 0x92, 0x88, 0x91, 0x23, 0x17,
	0x7b, 0x38, 0xc4, 0x2e, 0x21, 0x33, 0x2e, 0xfe, 0xe0, 0xd2, 0xa4, 0xe2, 0xe4, 0xa2, 0xcc, 0xa4,
	0x54, 0x88, 0x29, 0x42, 0x7c, 0x7a, 0x28, 0xf6, 0x4a, 0xf1, 0xeb, 0xa1, 0x1a, 0xaf, 0xc1, 0x68,
	0xc0, 0xe8, 0x64, 0x14, 0x65, 0x90, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab,
	0x9f, 0x96, 0x5a, 0x94, 0x9c, 0x5a, 0x96, 0x99, 0x6d, 0x6e, 0x64, 0xa9, 0x1f, 0x1c, 0xe2, 0xe3,
	0xed, 0x1a, 0x04, 0xf3, 0x8c, 0x6e, 0x62, 0x41, 0xa6, 0x3e, 0xc4, 0x7f, 0x49, 0x6c, 0x60, 0xda,
	0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x28, 0x62, 0x21, 0x61, 0xf0, 0x00, 0x00, 0x00,
}
