// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/watcher.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Currencies is the enum which represents the allowed currencies for the API
// USD is the default currency
type Currencies int32

const (
	Currencies_USD Currencies = 0
	Currencies_EUR Currencies = 1
	Currencies_JPY Currencies = 2
	Currencies_BGN Currencies = 3
	Currencies_CZK Currencies = 4
	Currencies_DKK Currencies = 5
	Currencies_GBP Currencies = 6
	Currencies_HUF Currencies = 7
	Currencies_PLN Currencies = 8
	Currencies_RON Currencies = 9
	Currencies_SEK Currencies = 10
	Currencies_CHF Currencies = 11
	Currencies_ISK Currencies = 12
	Currencies_NOK Currencies = 13
	Currencies_HRK Currencies = 14
	Currencies_RUB Currencies = 15
	Currencies_TRY Currencies = 16
	Currencies_AUD Currencies = 17
	Currencies_BRL Currencies = 18
	Currencies_CAD Currencies = 19
	Currencies_CNY Currencies = 20
	Currencies_HKD Currencies = 21
	Currencies_IDR Currencies = 22
	Currencies_ILS Currencies = 23
	Currencies_INR Currencies = 24
	Currencies_KRW Currencies = 25
	Currencies_MXN Currencies = 26
	Currencies_MYR Currencies = 27
	Currencies_NZD Currencies = 28
	Currencies_PHP Currencies = 29
	Currencies_SGD Currencies = 30
	Currencies_THB Currencies = 31
	Currencies_ZAR Currencies = 32
)

var Currencies_name = map[int32]string{
	0:  "USD",
	1:  "EUR",
	2:  "JPY",
	3:  "BGN",
	4:  "CZK",
	5:  "DKK",
	6:  "GBP",
	7:  "HUF",
	8:  "PLN",
	9:  "RON",
	10: "SEK",
	11: "CHF",
	12: "ISK",
	13: "NOK",
	14: "HRK",
	15: "RUB",
	16: "TRY",
	17: "AUD",
	18: "BRL",
	19: "CAD",
	20: "CNY",
	21: "HKD",
	22: "IDR",
	23: "ILS",
	24: "INR",
	25: "KRW",
	26: "MXN",
	27: "MYR",
	28: "NZD",
	29: "PHP",
	30: "SGD",
	31: "THB",
	32: "ZAR",
}

var Currencies_value = map[string]int32{
	"USD": 0,
	"EUR": 1,
	"JPY": 2,
	"BGN": 3,
	"CZK": 4,
	"DKK": 5,
	"GBP": 6,
	"HUF": 7,
	"PLN": 8,
	"RON": 9,
	"SEK": 10,
	"CHF": 11,
	"ISK": 12,
	"NOK": 13,
	"HRK": 14,
	"RUB": 15,
	"TRY": 16,
	"AUD": 17,
	"BRL": 18,
	"CAD": 19,
	"CNY": 20,
	"HKD": 21,
	"IDR": 22,
	"ILS": 23,
	"INR": 24,
	"KRW": 25,
	"MXN": 26,
	"MYR": 27,
	"NZD": 28,
	"PHP": 29,
	"SGD": 30,
	"THB": 31,
	"ZAR": 32,
}

func (x Currencies) String() string {
	return proto.EnumName(Currencies_name, int32(x))
}

func (Currencies) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_606cf1056908c0d2, []int{0}
}

type TickerRequest struct {
	Ticker               string     `protobuf:"bytes,1,opt,name=Ticker,proto3" json:"Ticker,omitempty"`
	Destination          Currencies `protobuf:"varint,2,opt,name=Destination,proto3,enum=Currencies" json:"Destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *TickerRequest) Reset()         { *m = TickerRequest{} }
func (m *TickerRequest) String() string { return proto.CompactTextString(m) }
func (*TickerRequest) ProtoMessage()    {}
func (*TickerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_606cf1056908c0d2, []int{0}
}

func (m *TickerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TickerRequest.Unmarshal(m, b)
}
func (m *TickerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TickerRequest.Marshal(b, m, deterministic)
}
func (m *TickerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TickerRequest.Merge(m, src)
}
func (m *TickerRequest) XXX_Size() int {
	return xxx_messageInfo_TickerRequest.Size(m)
}
func (m *TickerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TickerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TickerRequest proto.InternalMessageInfo

func (m *TickerRequest) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

func (m *TickerRequest) GetDestination() Currencies {
	if m != nil {
		return m.Destination
	}
	return Currencies_USD
}

type TickerResponse struct {
	Symbol               string   `protobuf:"bytes,1,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	Open                 string   `protobuf:"bytes,2,opt,name=Open,proto3" json:"Open,omitempty"`
	High                 string   `protobuf:"bytes,3,opt,name=High,proto3" json:"High,omitempty"`
	Low                  string   `protobuf:"bytes,4,opt,name=Low,proto3" json:"Low,omitempty"`
	Price                string   `protobuf:"bytes,5,opt,name=Price,proto3" json:"Price,omitempty"`
	Volume               string   `protobuf:"bytes,6,opt,name=Volume,proto3" json:"Volume,omitempty"`
	LTD                  string   `protobuf:"bytes,7,opt,name=LTD,proto3" json:"LTD,omitempty"`
	PrevClose            string   `protobuf:"bytes,8,opt,name=PrevClose,proto3" json:"PrevClose,omitempty"`
	Change               string   `protobuf:"bytes,9,opt,name=Change,proto3" json:"Change,omitempty"`
	PercentChange        string   `protobuf:"bytes,10,opt,name=PercentChange,proto3" json:"PercentChange,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TickerResponse) Reset()         { *m = TickerResponse{} }
func (m *TickerResponse) String() string { return proto.CompactTextString(m) }
func (*TickerResponse) ProtoMessage()    {}
func (*TickerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_606cf1056908c0d2, []int{1}
}

func (m *TickerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TickerResponse.Unmarshal(m, b)
}
func (m *TickerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TickerResponse.Marshal(b, m, deterministic)
}
func (m *TickerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TickerResponse.Merge(m, src)
}
func (m *TickerResponse) XXX_Size() int {
	return xxx_messageInfo_TickerResponse.Size(m)
}
func (m *TickerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TickerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TickerResponse proto.InternalMessageInfo

func (m *TickerResponse) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *TickerResponse) GetOpen() string {
	if m != nil {
		return m.Open
	}
	return ""
}

func (m *TickerResponse) GetHigh() string {
	if m != nil {
		return m.High
	}
	return ""
}

func (m *TickerResponse) GetLow() string {
	if m != nil {
		return m.Low
	}
	return ""
}

func (m *TickerResponse) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *TickerResponse) GetVolume() string {
	if m != nil {
		return m.Volume
	}
	return ""
}

func (m *TickerResponse) GetLTD() string {
	if m != nil {
		return m.LTD
	}
	return ""
}

func (m *TickerResponse) GetPrevClose() string {
	if m != nil {
		return m.PrevClose
	}
	return ""
}

func (m *TickerResponse) GetChange() string {
	if m != nil {
		return m.Change
	}
	return ""
}

func (m *TickerResponse) GetPercentChange() string {
	if m != nil {
		return m.PercentChange
	}
	return ""
}

type PriceResponse struct {
	Ticker               string   `protobuf:"bytes,1,opt,name=Ticker,proto3" json:"Ticker,omitempty"`
	StockPrice           float64  `protobuf:"fixed64,2,opt,name=StockPrice,proto3" json:"StockPrice,omitempty"`
	Currency             string   `protobuf:"bytes,3,opt,name=Currency,proto3" json:"Currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PriceResponse) Reset()         { *m = PriceResponse{} }
func (m *PriceResponse) String() string { return proto.CompactTextString(m) }
func (*PriceResponse) ProtoMessage()    {}
func (*PriceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_606cf1056908c0d2, []int{2}
}

func (m *PriceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceResponse.Unmarshal(m, b)
}
func (m *PriceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceResponse.Marshal(b, m, deterministic)
}
func (m *PriceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceResponse.Merge(m, src)
}
func (m *PriceResponse) XXX_Size() int {
	return xxx_messageInfo_PriceResponse.Size(m)
}
func (m *PriceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PriceResponse proto.InternalMessageInfo

func (m *PriceResponse) GetTicker() string {
	if m != nil {
		return m.Ticker
	}
	return ""
}

func (m *PriceResponse) GetStockPrice() float64 {
	if m != nil {
		return m.StockPrice
	}
	return 0
}

func (m *PriceResponse) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func init() {
	proto.RegisterEnum("Currencies", Currencies_name, Currencies_value)
	proto.RegisterType((*TickerRequest)(nil), "TickerRequest")
	proto.RegisterType((*TickerResponse)(nil), "TickerResponse")
	proto.RegisterType((*PriceResponse)(nil), "PriceResponse")
}

func init() { proto.RegisterFile("protos/watcher.proto", fileDescriptor_606cf1056908c0d2) }

var fileDescriptor_606cf1056908c0d2 = []byte{
	// 563 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xd1, 0x4f, 0xda, 0x50,
	0x14, 0xc6, 0x57, 0x51, 0x90, 0xeb, 0xc0, 0xb3, 0x3b, 0xe7, 0x3a, 0xe7, 0x9c, 0x31, 0x7b, 0x20,
	0x26, 0x16, 0xc3, 0xb2, 0x2c, 0x7b, 0x04, 0x8a, 0xe0, 0xca, 0x4a, 0x73, 0x0b, 0x3a, 0x78, 0x83,
	0xe6, 0x0a, 0x0d, 0xd0, 0xb2, 0xb6, 0x68, 0xfc, 0xc3, 0xf6, 0xef, 0x2d, 0xcb, 0x39, 0xb7, 0x4c,
	0x30, 0x7b, 0xea, 0xef, 0x7c, 0x37, 0xdf, 0xd7, 0xd3, 0x73, 0x7b, 0xd8, 0xc1, 0x22, 0x0a, 0x93,
	0x30, 0x2e, 0x3f, 0x0c, 0x13, 0x6f, 0x22, 0x23, 0x83, 0xca, 0xb3, 0x1b, 0x56, 0xe8, 0xfa, 0xde,
	0x54, 0x46, 0x42, 0xfe, 0x5a, 0xca, 0x38, 0xe1, 0x87, 0x2c, 0xab, 0x04, 0x5d, 0x3b, 0xd5, 0x4a,
	0x79, 0x91, 0x56, 0xfc, 0x82, 0xed, 0x99, 0x32, 0x4e, 0xfc, 0x60, 0x98, 0xf8, 0x61, 0xa0, 0x6f,
	0x9d, 0x6a, 0xa5, 0x62, 0x65, 0xcf, 0xa8, 0x2f, 0xa3, 0x48, 0x06, 0x9e, 0x2f, 0x63, 0xb1, 0x7e,
	0x7e, 0xf6, 0x47, 0x63, 0xc5, 0x55, 0x70, 0xbc, 0x08, 0x83, 0x58, 0x62, 0xb2, 0xfb, 0x38, 0x1f,
	0x85, 0xb3, 0x55, 0xb2, 0xaa, 0x38, 0x67, 0xdb, 0x9d, 0x85, 0x54, 0x91, 0x79, 0x41, 0x8c, 0x5a,
	0xcb, 0x1f, 0x4f, 0xf4, 0x8c, 0xd2, 0x90, 0x39, 0xb0, 0x4c, 0x3b, 0x7c, 0xd0, 0xb7, 0x49, 0x42,
	0xe4, 0x07, 0x6c, 0xc7, 0x89, 0x7c, 0x4f, 0xea, 0x3b, 0xa4, 0xa9, 0x02, 0xdf, 0x73, 0x13, 0xce,
	0x96, 0x73, 0xa9, 0x67, 0xd5, 0x7b, 0x54, 0x45, 0xfe, 0xae, 0xa9, 0xe7, 0x52, 0x7f, 0xd7, 0xe4,
	0xc7, 0x2c, 0xef, 0x44, 0xf2, 0xbe, 0x3e, 0x0b, 0x63, 0xa9, 0xef, 0x92, 0xfe, 0x24, 0x60, 0x4e,
	0x7d, 0x32, 0x0c, 0xc6, 0x52, 0xcf, 0xab, 0x1c, 0x55, 0xf1, 0x4f, 0xac, 0xe0, 0xc8, 0xc8, 0x93,
	0x41, 0x92, 0x1e, 0x33, 0x3a, 0xde, 0x14, 0xcf, 0x3c, 0x56, 0xa0, 0x76, 0xd6, 0x3f, 0xff, 0xbf,
	0x83, 0x3d, 0x61, 0xcc, 0x4d, 0x42, 0x6f, 0xaa, 0xbe, 0x04, 0x87, 0xa0, 0x89, 0x35, 0x85, 0x1f,
	0xb1, 0xdd, 0x74, 0xc8, 0x8f, 0xe9, 0x38, 0xfe, 0xd5, 0xe7, 0xbf, 0xb7, 0x18, 0x7b, 0xba, 0x01,
	0x9e, 0x63, 0x99, 0x9e, 0x6b, 0xc2, 0x0b, 0x84, 0x46, 0x4f, 0x80, 0x86, 0xf0, 0xdd, 0xe9, 0xc3,
	0x16, 0x42, 0xad, 0x69, 0x43, 0x06, 0xa1, 0x3e, 0xb0, 0x60, 0x1b, 0xc1, 0xb4, 0x2c, 0xd8, 0x41,
	0x68, 0xd6, 0x1c, 0xc8, 0x22, 0xb4, 0x7a, 0x57, 0x90, 0x43, 0x70, 0xda, 0x36, 0xec, 0x22, 0x88,
	0x8e, 0x0d, 0x79, 0x04, 0xb7, 0x61, 0x01, 0x23, 0x7b, 0xeb, 0x0a, 0xf6, 0x10, 0xae, 0x5d, 0x0b,
	0x5e, 0x22, 0xd8, 0x1d, 0x0b, 0x0a, 0x64, 0x17, 0x16, 0x14, 0xc9, 0xd5, 0xab, 0xc1, 0x3e, 0x42,
	0x57, 0xf4, 0x01, 0x10, 0xaa, 0x3d, 0x13, 0x5e, 0x51, 0x1b, 0xa2, 0x0d, 0x9c, 0x72, 0xaa, 0x26,
	0xbc, 0x26, 0xb0, 0xfb, 0x70, 0x40, 0x76, 0xcb, 0x84, 0x37, 0x94, 0x6c, 0x0a, 0x38, 0x24, 0x68,
	0xbb, 0xf0, 0x96, 0xc0, 0x16, 0xa0, 0x23, 0x58, 0xe2, 0x16, 0xde, 0x21, 0xfc, 0xf8, 0x69, 0xc3,
	0x11, 0x41, 0x5f, 0xc0, 0x7b, 0x6a, 0x63, 0x60, 0xc2, 0x31, 0x35, 0xdf, 0x72, 0xe0, 0x03, 0xf5,
	0xdc, 0x34, 0xe1, 0x84, 0xda, 0x68, 0xd5, 0xe0, 0x23, 0xc2, 0xa0, 0x2a, 0xe0, 0xb4, 0x32, 0x63,
	0xb9, 0x5b, 0xb5, 0x06, 0xfc, 0x9c, 0xe5, 0x9a, 0x32, 0xb9, 0x0e, 0xee, 0x42, 0x5e, 0x34, 0x36,
	0x56, 0xe1, 0x68, 0xdf, 0x78, 0xf6, 0x07, 0x7f, 0x61, 0xfb, 0xee, 0x72, 0x14, 0x7b, 0x91, 0x3f,
	0x92, 0xe9, 0xed, 0x3d, 0xf7, 0x14, 0x8d, 0x8d, 0x5b, 0x2f, 0x69, 0x97, 0x5a, 0xad, 0x32, 0xb8,
	0x1c, 0xfb, 0xc9, 0x64, 0x39, 0x32, 0xbc, 0x70, 0x5e, 0xbe, 0xc3, 0xdf, 0xe4, 0xde, 0x9f, 0x7e,
	0xad, 0x7c, 0x2b, 0xbb, 0xdd, 0xb6, 0xd5, 0x10, 0xab, 0x95, 0xbc, 0x18, 0x2e, 0xfc, 0xb2, 0xda,
	0xd2, 0x51, 0x96, 0x9e, 0x9f, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xa0, 0x3f, 0x73, 0xb6,
	0x03, 0x00, 0x00,
}
